= Rechtliche Hinweise
:allow-uri-read: 


<<<<<<< HEAD --- Permalink: legal-notices.html Seitenleiste: Seitenleisten-Schlüsselwörter: Zusammenfassung: ---



= Rechtliche Hinweise

[role="lead"]
Rechtliche Hinweise bieten Zugriff auf Urheberrechtserklärungen, Marken, Patente und mehr.



== Copyright

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marken

NETAPP, das NETAPP-Logo und die auf der NetApp -Markenseite aufgeführten Marken sind Marken von NetApp, Inc. Andere Firmen- und Produktnamen können Marken ihrer jeweiligen Eigentümer sein.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Patente

Eine aktuelle Liste der Patente im Besitz von NetApp finden Sie unter:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Datenschutzrichtlinie

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



== Open Source

Hinweisdateien enthalten Informationen zu Urheberrechten und Lizenzen Dritter, die in der NetApp -Software verwendet werden.

* https://docs.netapp.com/us-en/bluexp-setup-admin/media/notice.pdf["Hinweis zur NetApp Konsole"^]


[]
====
'''
Permalink: legal-notices.html Seitenleiste: Seitenleiste Schlüsselwörter: # keine Schlüsselwörter Zusammenfassung: # keine Zusammenfassung --- = Rechtliche Hinweise :icons: Schriftart :imagesdir: ./media/

[role="lead"]
Rechtliche Hinweise bieten Zugriff auf Urheberrechtserklärungen, Marken, Patente und mehr.

== Urheberrecht

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]

== Marken

NETAPP, das NETAPP-Logo und die auf der NetApp -Markenseite aufgeführten Marken sind Marken von NetApp, Inc. Andere Firmen- und Produktnamen können Marken ihrer jeweiligen Eigentümer sein.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]

== Patente

Eine aktuelle Liste der Patente im Besitz von NetApp finden Sie unter:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]

== Datenschutzerklärung

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]

== Open Source

Hinweisdateien enthalten Informationen zu Urheberrechten und Lizenzen Dritter, die in der NetApp -Software verwendet werden.

>>>>>>> db096cfa4bc2bcbc1a7a0fefc9249c9cbef4831b

====