---
settings:
  name: NetApp Ransomware Resilience
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    release_notes_repo: console-relnotes
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetApp Ransomware Resilience Dokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu bei Ransomware Resilience?
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/rp-reference-limitations.html"
  - title: Erste Schritte
    entries:
    - title: Erfahren Sie mehr über Ransomware-Resilienz
      url: "/concept-ransomware-resilience.html"
    - title: Voraussetzungen
      url: "/rp-start-prerequisites.html"
    - title: Schnellstart
      url: "/rp-start-quick-start.html"
    - title: Ransomware-Resilienz einrichten
      url: "/rp-start-setup.html"
    - title: Einrichten der Lizenzierung
      url: "/rp-start-licenses.html"
    - title: Workloads ermitteln
      url: "/rp-start-discover.html"
  - title: Nutzen Sie Ransomware-Resilienz
    entries:
    - title: Zugriff auf Ransomware-Resilienz
      url: "/rp-start-login.html"
    - title: Workload-Gesundheit anzeigen
      url: "/rp-use-dashboard.html"
    - title: Schützen und erkennen
      entries:
      - title: Schutz überprüfen
        url: "/task-review-protection.html"
      - title: Konfigurieren von Sicherungszielen
        url: "/task-backup-destination.html"
      - title: Workloads schützen
        url: "/rp-use-protect.html"
      - title: Benutzeraktivitätserkennung konfigurieren
        entries:
        - title: Erfahren Sie mehr über die Erkennung von Benutzeraktivitäten
          url: "/concept-user-behavior.html"
        - title: Anforderungen an die Erkennung von Benutzeraktivitäten
          url: "/reference-user-activity-requirements.html"
        - title: Agenten und Collector konfigurieren
          url: "/suspicious-user-activity.html"
      - title: Schutzgruppen verwalten
        url: "/task-protection-group.html"
      - title: Scannen nach personenbezogenen Daten
        url: "/task-classify.html"
    - title: Reagieren und wiederherstellen
      entries:
      - title: Auf eine erkannte Warnung reagieren
        url: "/rp-use-alert.html"
      - title: Überprüfung des Wiederherstellungsstatus
        url: "/rp-use-recover.html"
      - title: Wiederherstellung mit einer benutzerdefinierten Wiederherstellung
        url: "/rp-use-recover.html"
      - title: Führen Sie eine saubere Wiederherstellung durch
        entries:
        - title: Erstellen Sie eine isolierte Wiederherstellungsumgebung
          url: "/task-clean-restore.html"
        - title: Wiederherstellung mit sauberem Restore
          url: "/task-clean-restore-recover.html"
    - title: Führen Sie eine Bereitschaftsübung durch
      url: "/rp-start-simulate.html"
    - title: SIEM konfigurieren
      url: "/task-siem.html"
    - title: SOAR-Playbooks integrieren
      url: "/reference-soar.html"
    - title: Berichte herunterladen
      url: "/rp-use-reports.html"
  - section: support
  - title: FAQ
    url: "/rp-start-faq.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
