---
sidebar: sidebar 
permalink: reference-soar.html 
keywords: ransomware protection, soar, security orchestration, microsoft sentinel, splunk, automation, threat response, playbook 
summary: Integrieren und nutzen Sie SOAR-Playbooks, um Aufgaben zur Bedrohungsreaktion von NetApp Ransomware Resilience zu automatisieren. 
---
= Integrieren Sie ein SOAR-Playbook für NetApp Ransomware Resilience
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Ransomware Resilience bietet Security Orchestration, Automation, and Response (SOAR) Playbooks, die die Automatisierung von Aufgaben wie der Reaktion auf Bedrohungen ermöglichen.

Ransomware Resilience Playbooks bieten die folgenden Funktionen:

* Benutzer blockieren/entsperren*
* Erstellen Sie einen Snapshot eines Volumes
* Eine IP-Adresse mit Bedrohungsdaten anreichern
* Speicherinformationen für einen bestimmten Agenten und ein bestimmtes System anreichern
* Nehmen Sie ein Volume zur Reaktion auf einen Vorfall offline oder nehmen Sie ein Volume nach einem Vorfall wieder online.
* Konnektivität testen
* Überprüfen Sie den Status eines Enrichment-Jobs


{asterisk}Das Blockieren/Entsperren eines Benutzers wird nur für Splunk- und Google SecOps SOAR-Playbooks unterstützt. Sie müssen link:concept-user-behavior["Erkennung des Nutzerverhaltens"] auf einem unterstützten System konfiguriert haben, um einen Benutzer zu blockieren.



[[playbooks]]
== Playbooks

Ransomware Resilience bietet Playbooks für Google SecOps, Microsoft Sentinel und Splunk. Auf der entsprechenden Seite sind Details zur Einrichtung zu finden.

* link:https://github.com/chronicle/content-hub/tree/main/content/response_integrations/third_party/partner/netappransomwareresilience["Google SecOps"^]
* link:https://marketplace.microsoft.com/en-us/product/netapp.azure-sentinel-solution-netapprrs?tab=Overview["Microsoft Sentinel"^] | link:https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/NetApp%20Ransomware%20Resilience/Playbooks["GitHub-Link"^]
* link:https://github.com/splunk-soar-connectors/netappransomwareresilience["Splunk"^]
+
Für Splunk Cloud müssen Sie die Plattformversion 7.0, 7.1, 7.2, 8.0 oder 8.4 ausführen. Weitere Informationen finden Sie unter link:https://splunkbase.splunk.com/app/8483["Splunkbase"^].




NOTE: Für Azure NetApp Files-Systeme überprüfen Sie die link:rp-reference-limitations.html["Einschränkungen für Azure NetApp Files"] mit SOAR.

.Weitere Informationen
* link:task-siem.html["Verbinden Sie NetApp Ransomware Resilience mit einem SIEM für Bedrohungsanalyse und -erkennung"]

