---
sidebar: sidebar 
permalink: rp-reference-limitations.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Produktversion nicht unterstützt werden. 
---
= Bekannte Einschränkungen in NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen kennzeichnen Plattformen, Geräte oder Funktionen, die von dieser Produktversion nicht unterstützt werden oder nicht ordnungsgemäß mit ihr zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.



[[readiness-drill-reset-option-issue]]
== Problem mit der Option zum Zurücksetzen der Readiness drill

Wenn Sie für die Übung zur Vorbereitung auf Ransomware-Angriffe ein ONTAP 9.11.1-Volume auswählen, sendet Ransomware Resilience eine Warnung.  Wenn Sie die Daten mit der Option „Auf Volume klonen“ wiederherstellen und den Drill zurücksetzen, schlägt der Rücksetzvorgang fehl.



[[amazon-fsx-for-netapp-ontap-limitations]]
== Einschränkungen von Amazon FSx for NetApp ONTAP

Die folgenden Einschränkungen gelten für Amazon FSx für ONTAP:

* Backup-Richtlinien werden für Amazon FSx für ONTAP nicht unterstützt. In dieser Umgebung sollten Sicherungsvorgänge mit Amazon FSx Backups durchgeführt werden. Diese Workloads können mit Ransomware Resilience wiederhergestellt werden.
* Wiederherstellungsvorgänge werden nur von Snapshots aus durchgeführt.




[[azure-netapp-files-limitations]]
== Azure NetApp Files-Einschränkungen

Für Azure NetApp Files gelten die folgenden Einschränkungen:

* Ransomware-Schutzstrategien mit Backup-Richtlinien werden für Azure NetApp Files nicht unterstützt. Stattdessen können Sie Azure NetApp Files Backup verwenden.
* Ransomware-Schutzstrategien mit Replikation werden für Azure NetApp Files nicht unterstützt.
* Azure NetApp Files unterstützt weder FPolicy noch die Erkennung des Nutzerverhaltens. Azure NetApp Files unterstützt auch keine Entropieforensik.
* Achten Sie bei der Auswahl einer Schutzstrategie darauf, dass deren Snapshot-Zeitplan mit Azure NetApp Files kompatibel ist. Der am häufigsten in Azure NetApp Files verfügbare Snapshot-Zeitplan ist stündlich.
* Von der Verwendung link:reference-soar.html["SOAR-Spielbücher"] mit Azure NetApp Files wird abgeraten, da die Azure NetApp Files APIs automatisierte Aktionen blockieren.
* Einige Ereignisdaten sind in link:task-siem.html["SIEM-Berichte"] für Azure NetApp Files-Konfigurationen nicht enthalten.




[[google-cloud-netapp-volumes-limitations]]
== Google Cloud NetApp Volumes-Beschränkungen

Für Google Cloud NetApp Volumes gelten folgende Einschränkungen:

* Derzeit können Sie auf Google Cloud NetApp Volumes-Workloads nur Verschlüsselungs- und FPolicy-basierte Schutzstrategien anwenden. Sie können keine Strategien zum Schutz des Nutzerverhaltens anwenden.
* Schutzstrategien mit Replikation werden für Google Cloud NetApp Volumes derzeit nicht unterstützt.




[[san-storage-limitations]]
== SAN Speicherbeschränkungen

Für SAN (Blockspeicher)-Workloads gelten die folgenden Einschränkungen:

* Wenn Ransomware Resilience Warnungen für SAN Workloads generiert, basieren diese Warnungen ausschließlich auf hoher Entropie.
* SAN Workloads können nur mithilfe einer link:task-custom-restore.html["benutzerdefinierte Wiederherstellung"] wiederhergestellt werden. Eine Clean Restore ist für SAN Workloads derzeit nicht verfügbar.




[[multi-admin-verification]]
== Multi-Admin-Verifizierung

Die Multi-Admin-Verifizierung wird in Ransomware Resilience oder der NetApp Console nicht unterstützt. Wenn link:https://docs.netapp.com/us-en/ontap/multi-admin-verify/["Multi-Admin Verifizierung in ONTAP"^] konfiguriert wurde, ist es nicht möglich, den Schutz zu aktivieren, eine Bereitschaftsübung durchzuführen oder Wiederherstellungsvorgänge vorzunehmen. Vor dem Versuch eines dieser Vorgänge sollte die Multi-Admin-Verifizierung deaktiviert werden.
