---
sidebar: sidebar 
permalink: rp-reference-limitations.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Produktversion nicht unterstützt werden. 
---
= Bekannte Einschränkungen in NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen kennzeichnen Plattformen, Geräte oder Funktionen, die von dieser Produktversion nicht unterstützt werden oder nicht ordnungsgemäß mit ihr zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.



== Problem mit der Reset-Option für die Bereitschaftsübung

Wenn Sie für die Übung zur Vorbereitung auf Ransomware-Angriffe ein ONTAP 9.11.1-Volume auswählen, sendet Ransomware Resilience eine Warnung.  Wenn Sie die Daten mit der Option „Auf Volume klonen“ wiederherstellen und den Drill zurücksetzen, schlägt der Rücksetzvorgang fehl.



== Einschränkungen von Amazon FSx for NetApp ONTAP

Die folgenden Einschränkungen gelten für Amazon FSx für ONTAP:

* Backup-Richtlinien werden für Amazon FSx for ONTAP nicht unterstützt. In dieser Umgebung sollten Sie Sicherungsvorgänge mit Amazon FSx for ONTAP-Backups durchführen. Sie können diese Workloads mit Ransomware Resilience wiederherstellen.
* Wiederherstellungsvorgänge werden nur von Snapshots aus durchgeführt.




== Azure NetApp Files-Einschränkungen

Für Azure NetApp Files gelten die folgenden Einschränkungen:

* Ransomware-Schutzstrategien mit Backup-Richtlinien werden für Azure NetApp Files nicht unterstützt. Stattdessen können Sie Azure NetApp Files Backup verwenden.
* Ransomware-Schutzstrategien mit Replikation werden für Azure NetApp Files nicht unterstützt.
* Azure NetApp Files unterstützt weder FPolicy noch Benutzeraktivitäten. Azure NetApp Files unterstützt auch keine Entropie-Forensik.
* Achten Sie bei der Auswahl einer Schutzstrategie darauf, dass deren Snapshot-Zeitplan mit Azure NetApp Files kompatibel ist. Der am häufigsten in Azure NetApp Files verfügbare Snapshot-Zeitplan ist stündlich.
* Von der Verwendung link:reference-soar.html["SOAR-Spielbücher"] mit Azure NetApp Files wird abgeraten, da die Azure NetApp Files APIs automatisierte Aktionen blockieren.
* Einige Ereignisdaten sind in link:task-siem.html["SIEM-Berichte"] für Azure NetApp Files-Konfigurationen nicht enthalten.




== Google Cloud NetApp Volumes-Beschränkungen

Für Google Cloud NetApp Volumes gelten folgende Einschränkungen:

* Derzeit können Sie auf Google Cloud NetApp Volumes-Workloads nur Verschlüsselungs- und FPolicy-basierte Schutzstrategien anwenden. Sie können keine Schutzstrategien für Benutzeraktivitäten anwenden.
* Schutzstrategien mit Replikation werden derzeit für Google Cloud NetApp Volumes nicht unterstützt

