---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: Beginnen Sie mit NetApp Ransomware Resilience, indem Sie die Unterstützung für Ihre Umgebung, Ihren Netzwerkzugriff, Ihre Anmeldung und Ihren Webbrowser überprüfen. 
---
= Voraussetzungen für NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Um eine erfolgreiche Implementierung von NetApp Ransomware Resilience zu gewährleisten, überprüfen Sie die Einsatzbereitschaft Ihrer Betriebsumgebung, Netzwerkzugriff und Ihres Webbrowsers.

Überprüfen Sie und stellen Sie sicher, dass Sie die folgenden Anforderungen erfüllen.



== Unterstützte Systeme

Stellen Sie sicher, dass Sie ein unterstütztes System verwenden:

|===
| Umfeld | Protokoll | Unterstützte Versionen 


| Amazon FSx for NetApp ONTAP* | CIFS, NFS und SAN | k. A. 


| Azure NetApp Files | CIFS & NFS | k. A. 


.2+| Cloud Volumes ONTAP für AWS | CIFS & NFS | 9.11.1 und später 


| SAN (iSCSI & NVMe) | 9.17.1 und höher 


.2+| Cloud Volumes ONTAP für Google Cloud Platform | CIFS & NFS | 9.11.1 und später 


| SAN (iSCSI & NVMe) | 9.17.1 und höher 


.2+| Cloud Volumes ONTAP für Microsoft Azure | CIFS & NFS | 9.12.1 und später 


| SAN (iSCSI & NVMe) | 9.17.1 und höher 


.2+| ONTAP (lokal) | CIFS & NFS | 9.11.1 und später 


| SAN (iSCSI & NVMe) | 9.17.1 und höher 


| Google Cloud NetApp Volumes | CIFS, NFS, SAN (iSCSI & NVMe) | k. A. 
|===
{* Amazon FSx for NetApp ONTAP verwendet Autonomous Ransomware Protection (ARP) und nicht ARP/AI.  Weitere Informationen zu den Unterschieden finden Sie unterlink:https://docs.netapp.com/us-en/ontap/anti-ransomware/#arp-ai["ARP/AI"^] Die


NOTE: Die Erkennung von Benutzeraktivitäten wird für Azure NetApp Files oder Google Cloud NetApp Volumes nicht unterstützt. Weitere Informationen zur Unterstützung der Erkennung von Benutzeraktivitäten finden Sie unter link:reference-user-activity-requirements.html["Anforderungen an die Erkennung von Benutzeraktivitäten"].



== NetApp Console

Ihre NetApp Console Konfiguration erfordert Folgendes:

* Ein NetApp Console mit Organisationsadministratorberechtigungen zum Erkennen von Ressourcen.
* Eine Konsolenorganisation und ein System mit mindestens einem aktiven Konsolenagenten, der mit einem System verbunden istlink:concept-ransomware-resilience.html#supported-backup-targets-systems-and-workload-data-sources["Unterstütztes System"] Die
+
** Falls Ihre On-Premises ONTAP Cluster oder Cloud Volumes ONTAP Systeme nicht in der Console eingerichtet sind, siehe link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Erfahren Sie, wie Sie einen Konsolenagenten konfigurieren"^] und link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Standardanforderungen für die Konsole"^].
+

NOTE: Wenn Sie mehrere Console-Agenten in einer einzigen Console-Organisation haben, scannt Ransomware Resilience ONTAP Ressourcen auf allen Console-Agenten, die nicht aktuell in der Console-Benutzeroberfläche ausgewählt sind.



* Der Konsolenagent muss über die `cloudmanager-ransomware-protection` Container in einem aktiven Zustand.
* Für ONTAP oder Cloud Volumes ONTAP Cluster ist für die Ransomware-Resilienz ONTAP Version 9.11.1 oder höher erforderlich.
+

NOTE: Um Ransomware Resilience auf SAN-Workloads nutzen zu können, müssen Sie ONTAP 9.17.1 oder höher verwenden.





== ONTAP Anforderungen

* Sie müssen ONTAP 9.11.1 oder höher mit einer auf der lokalen ONTAP -Instanz aktivierten ONTAP One-Lizenz verwenden.  Weitere Informationen zur ONTAP Unterstützung finden Sie unterlink:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Übersicht über den autonomen Ransomware-Schutz"^] Die
* Um Schutzkonfigurationen anzuwenden (z. B. die Aktivierung des autonomen Ransomware-Schutzes), benötigt Ransomware Resilience Administratorrechte auf dem ONTAP Cluster. Das Onboarding des ONTAP Clusters sollte ausschließlich mit den Anmeldeinformationen des ONTAP Cluster-Administratorbenutzers erfolgen.



NOTE: Wenn Sie einen ONTAP Cluster mit der Konsole mit Nicht-Administrator-Anmeldeinformationen verbunden haben, müssen Sie <<Aktualisieren Sie die Berechtigungen von Nicht-Administratorbenutzern in einem ONTAP -System>>.



== Datensicherungen

* Ein Konto in NetApp StorageGRID, AWS S3, Azure Blob oder Google Cloud Platform für Backup-Ziele mit entsprechend konfigurierten Zugriffsberechtigungen.
+
Weitere Informationen finden Sie im https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS-, Azure- oder S3-Berechtigungsliste"^] für Details.




NOTE: Sie können link:task-backup-destination.html["Konfigurieren eines Backup-Ziels in Ransomware Resilience"]. Wenn Ihre Workloads durch NetApp Backup and Recovery geschützt sind, erkennt Ransomware Resilience automatisch die Schutzdetails, einschließlich Snapshots und Backup-Ziele. Backup and Recovery ist _nicht_ erforderlich, um Ransomware Resilience zu verwenden.



== Anforderungen an die Erkennung des Nutzerverhaltens

Damit Ransomware Resilience Warnungen zum Benutzerverhalten ausgeben kann, müssen Sie einen Benutzeraktivitätsagenten konfigurieren. Um einen Benutzeraktivitätsagenten zu installieren, stellen Sie sicher, dass Ihr System link:reference-user-activity-requirements.html["die Anforderungen"] erfüllt.



== Voraussetzungen für die Bereinigung der Wiederherstellung

Ransomware Resilience bietet eine saubere Wiederherstellung, die einen geführten Wiederherstellungsprozess zur Ermittlung optimaler Wiederherstellungspfade beinhaltet. Um eine saubere Wiederherstellung zu nutzen, link:task-clean-restore.html["Stellen Sie sicher, dass Sie die Voraussetzungen erfüllen."].



== Aktualisieren Sie die Berechtigungen von Nicht-Administratorbenutzern in einem ONTAP -System

Wenn Sie die Berechtigungen von Benutzern ohne Administratorrechte für ein bestimmtes System aktualisieren müssen, gehen Sie wie folgt vor:

. Melden Sie sich in der Konsole an. Identifizieren Sie im Dashboard das System, dessen ONTAP Benutzerberechtigungen aktualisiert werden müssen.
. Wählen Sie das System aus, um dessen Details anzuzeigen.
. Wählen Sie *Zusätzliche Informationen anzeigen*, um den Benutzernamen anzuzeigen.
. Melden Sie sich als Administrator an der ONTAP Cluster-CLI an.
. Zeigen Sie die vorhandenen Rollen für diesen Benutzer an:
+
[listing]
----
security login show -user-or-group-name <username>
----
. Ändern Sie die Rolle für den Benutzer. Eingeben:
+
[listing]
----
security login modify -user-or-group-name <name> -application console|http|ontapi|ssh -authentication-method password -role admin
----
. Kehren Sie zur NetApp Console zurück, um die Ransomware-Resilienz zu nutzen.

