---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: Beginnen Sie mit NetApp Ransomware Resilience, indem Sie die Unterstützung für Ihre Umgebung, Ihren Netzwerkzugriff, Ihre Anmeldung und Ihren Webbrowser überprüfen. 
---
= Voraussetzungen für NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Beginnen Sie mit NetApp Ransomware Resilience, indem Sie die Bereitschaft Ihrer Betriebsumgebung, Ihres Netzwerkzugriffs und Ihres Webbrowsers überprüfen.

Um Ransomware Resilience nutzen zu können, müssen Sie die Voraussetzungen erfüllen.



== Unterstützte Systeme

Stellen Sie sicher, dass Sie ein unterstütztes System verwenden:

|===
| Umfeld | Protokoll | Unterstützte Versionen 


| Amazon FSx for NetApp ONTAP* | NFS, CIFS und SAN | k. A. 


.2+| Cloud Volumes ONTAP für AWS | CIFS & NFS | 9.11.1 und später 


| SAN (FC, iSCSI & NVMe) | 9.17.1 und höher 


.2+| Cloud Volumes ONTAP für Google Cloud Platform | CIFS & NFS | 9.11.1 und später 


| SAN (FC, iSCSI & NVMe) | 9.17.1 und höher 


.2+| Cloud Volumes ONTAP für Microsoft Azure | CIFS & NFS | 9.12.1 und später 


| SAN (FC, iSCSI & NVMe) | 9.17.1 und höher 


.2+| ONTAP (lokal) | CIFS & NFS | 9.11.1 und später 


| SAN (FC, iSCSI & NVMe) | 9.17.1 und höher 
|===
{* Amazon FSx for NetApp ONTAP verwendet Autonomous Ransomware Protection (ARP) und nicht ARP/AI.  Weitere Informationen zu den Unterschieden finden Sie unterlink:https://docs.netapp.com/us-en/ontap/anti-ransomware/#arp-ai["ARP/AI"^] Die



== NetApp Console

Ihre NetApp Console Konfiguration erfordert Folgendes:

* Ein NetApp Console mit Organisationsadministratorberechtigungen zum Erkennen von Ressourcen.
* Eine Konsolenorganisation und ein System mit mindestens einem aktiven Konsolenagenten, der mit einem System verbunden istlink:concept-ransomware-resilience.html#supported-backup-targets-systems-and-workload-data-sources["Unterstütztes System"] Die
+
** Falls Ihre lokalen ONTAP Cluster oder Cloud Volumes ONTAP in AWS oder in der Azure-Cloud nicht in der Konsole eingerichtet sind, siehelink:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Erfahren Sie, wie Sie einen Konsolenagenten konfigurieren"^] Undlink:https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Standardanforderungen für die Konsole"^] Die
+

NOTE: Wenn Sie mehrere Konsolenagenten in einer einzigen Konsolenorganisation haben, scannt Ransomware Resilience die ONTAP -Ressourcen aller Konsolenagenten über den derzeit in der Konsolen-Benutzeroberfläche ausgewählten Agenten hinaus.



* Der Konsolenagent muss über die `cloudmanager-ransomware-protection` Container in einem aktiven Zustand.
* Mindestens ein Konsolensystem mit einem lokalen NetApp ONTAP -Cluster oder Cloud Volumes ONTAP in AWS oder Azure.  Ransomware Resilience unterstützt sowohl NAS- (NFS und SMB) als auch SAN-Protokolle (iSCSI, FC und NVMe).
+
** Ransomware Resilience wird mit ONTAP oder Cloud Volumes ONTAP Clustern mit ONTAP Version 9.11.1 oder höher unterstützt.
+

NOTE: Um Ransomware Resilience auf SAN-Workloads nutzen zu können, müssen Sie ONTAP 9.17.1 oder höher verwenden.







== ONTAP Anforderungen

* Sie müssen ONTAP 9.11.1 oder höher mit einer auf der lokalen ONTAP -Instanz aktivierten ONTAP One-Lizenz verwenden.  Weitere Informationen zur ONTAP Unterstützung finden Sie unterlink:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Übersicht über den autonomen Ransomware-Schutz"^] Die
* Um Schutzkonfigurationen anzuwenden (z. B. die Aktivierung des autonomen Ransomware-Schutzes), benötigt Ransomware Resilience Administratorrechte auf dem ONTAP Cluster. Das Onboarding des ONTAP Clusters sollte ausschließlich mit den Anmeldeinformationen des ONTAP Cluster-Administratorbenutzers erfolgen.



NOTE: Wenn Sie einen ONTAP Cluster mit der Konsole mit Nicht-Administrator-Anmeldeinformationen verbunden haben, [müssen Sie die Anmeldeinformationen im ONTAP -Cluster aktualisieren](#update-non-admin-user-permissions-in-an-ontap-system).



== Datensicherungen

* Ein Konto in NetApp StorageGRID, AWS S3, Azure Blob oder Google Cloud Platform für Backup-Ziele mit entsprechend konfigurierten Zugriffsberechtigungen.
+
Weitere Informationen finden Sie im https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS-, Azure- oder S3-Berechtigungsliste"^] für Details.

* NetApp Backup and Recovery muss auf dem System nicht aktiviert werden.
+
Ransomware Resilience hilft bei der Konfiguration eines Sicherungsziels über die Option „Einstellungen“. Sehen link:rp-use-settings.html["Konfigurieren der Einstellungen"] .





== Anforderungen an verdächtiges Nutzerverhalten

Damit NetApp Ransomware Resilience Warnungen über verdächtiges Benutzerverhalten ausgeben kann, müssen Sie einen Benutzeraktivitätsagenten konfigurieren. Um einen Benutzeraktivitätsagenten zu installieren, stellen Sie sicher, dass Ihr System link:reference-user-activity-requirements.html["die Anforderungen"] erfüllt.



== Aktualisieren Sie die Berechtigungen von Nicht-Administratorbenutzern in einem ONTAP -System

Wenn Sie die Berechtigungen von Nicht-Admin-Benutzern für ein bestimmtes System aktualisieren müssen, verwenden Sie diese Verfahrensschritte.

. Melden Sie sich in der Console an. Identifizieren Sie im Dashboard das System, dessen ONTAP Benutzerberechtigungen aktualisiert werden müssen.
. Wählen Sie das System aus, um dessen Details anzuzeigen.
. Wählen Sie *Zusätzliche Informationen anzeigen*, um den Benutzernamen anzuzeigen.
. Melden Sie sich als Administrator an der ONTAP Cluster-CLI an.
. Zeigen Sie die vorhandenen Rollen für diesen Benutzer an:
+
[listing]
----
security login show -user-or-group-name <username>
----
. Ändern Sie die Rolle für den Benutzer. Eingeben:
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. Kehren Sie zur NetApp Console zurück, um die Ransomware-Resilienz zu nutzen.

