---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Finden Sie eine Antwort auf eine häufig gestellte Frage zu NetApp Ransomware Resilience. 
---
= Häufig gestellte Fragen zur NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Diese FAQ können hilfreich sein, wenn Sie nur eine schnelle Antwort auf eine Frage zu NetApp Ransomware Resilience suchen.



== Einsatz

.Benötigen Sie eine Lizenz zur Nutzung von Ransomware Resilience?
Sie können die folgenden Lizenztypen verwenden:

* Melden Sie sich für eine 30-tägige kostenlose Testversion an.
* Erwerben Sie ein Pay-as-you-go-Abonnement (PAYGO) für NetApp Intelligent Services und Ransomware Resilience über Amazon Web Services (AWS) Marketplace, Google Cloud Marketplace und Microsoft Azure Marketplace.
* Bringen Sie Ihre eigene Lizenz mit (BYOL). Dabei handelt es sich um eine NetApp -Lizenzdatei (NLF), die Sie von Ihrem NetApp Vertriebsmitarbeiter erhalten. Sie können die Lizenzseriennummer verwenden, um BYOL im Bereich „Licenses and subscriptions“ der Konsole zu aktivieren.


.Wie aktiviert man die Ransomware-Resilienz?
Sie können über die NetApp Console auf Ransomware Resilience zugreifen. Stellen Sie sicher, dass Sie link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["Zugriffsrollen"] Und link:rp-start-prerequisites.html["Voraussetzungen"]Die Wenn Sie einen Konsolenagenten erfolgreich konfiguriert haben, können Sie dann link:rp-start-discover.html["Arbeitslasten ermitteln"]Die

Weitere Informationen finden Sie unterlink:rp-start-login.html["Zugriff auf Ransomware-Resilienz"] Undlink:rp-start-quick-start.html["Schnellstartanleitung zur Ransomware-Resilienz"] .

.Ist die Ransomware-Resilienz in den Modi Standard, eingeschränkt und privat verfügbar?
Die Ransomware-Resilienz ist derzeit nur im Standardmodus verfügbar.

Eine Erläuterung dieser Modi für alle NetApp -Datendienste finden Sie unter https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Bereitstellungsmodi der NetApp Console"^] .



== Zugang

.Wie lautet die URL für Ransomware-Resilienz?
Geben Sie im Browser Folgendes ein: https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^] um auf die Konsole zuzugreifen.

.Wie werden Zugriffsberechtigungen gehandhabt?
https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Konsolenzugriffsrollen für alle Dienste"^]. Ransomware-Resilienz hat auch link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-ransomware-roles.html["dedizierte Zugriffsrollen"^]Die

.Welche Geräteauflösung ist am besten geeignet?
Die empfohlene Geräteauflösung für Ransomware Resilience beträgt 1920 x 1080 oder besser.

.Welchen Browser soll ich verwenden?
Sie können mit jedem modernen Webbrowser auf die NetApp Console zugreifen.



== Interoperabilität

.Ist die Ransomware-Resilienz auf die Schutzeinstellungen in ONTAP vorbereitet?
Ja, Ransomware Resilience erkennt in ONTAP festgelegte Snapshot-Zeitpläne.

.Wie interagiert Ransomware Resilience mit NetApp Backup and Recovery und SnapCenter?
Ransomware Resilience arbeitet mit Backup und Recovery zusammen, um Snapshot- und Backup-Richtlinien für Dateifreigabe-Workloads zu ermitteln und festzulegen.

Ransomware Resilience arbeitet mit SnapCenter oder SnapCenter für VMware zusammen, um Snapshot- und Backup-Richtlinien für Anwendungs- und VM-Workloads zu ermitteln und festzulegen.

Ransomware Resilience arbeitet außerdem mit Backup and Recovery und SnapCenter (einschließlich SnapCenter für VMware) zusammen, um eine datei- und workloadkonsistente Wiederherstellung durchzuführen.

Für Lizenzierung und Abrechnung kann Ransomware Resilience auch dann in Backup and Recovery integriert werden, wenn Sie keine separate Lizenz für Backup and Recovery besitzen. Wenn Sie sowohl über Backup and Recovery als auch über Ransomware Resilience verfügen, werden alle gemeinsamen Daten, die durch beide Produkte geschützt werden, nur über Ransomware Resilience abgerechnet.



== Arbeitslasten

.Was versteht man unter Arbeitslast im Kontext von Ransomware-Resilienz?
Eine Workload ist eine Anwendung, eine VM oder eine Dateifreigabe. Eine Arbeitslast umfasst alle Volumes, die von einer einzelnen Anwendungsinstanz verwendet werden.

Betrachten wir beispielsweise eine Oracle-Datenbank, die auf ora3.host.com bereitgestellt ist mit `vol1` enthaltend Daten und `vol2` enthaltend Protokolle. Die beiden Volumes bilden die Arbeitslast für diese Oracle-Datenbankinstanz.

.Wie priorisiert Ransomware Resilience die Workload-Daten?
Die Priorität der Arbeitslast (kritisch, Standard, wichtig) wird durch die Snapshot-Frequenzen bestimmt, die bereits für jedes mit der Arbeitslast verbundene Volume und die geplanten Backups angewendet wurden.

link:rp-use-protect.html["Informieren Sie sich über die Priorität oder Wichtigkeit der Arbeitslast"] .

.Welche Workloads werden von Ransomware Resilience unterstützt?
Ransomware Resilience kann die folgenden Workloads identifizieren: Oracle, Dateifreigaben, Blockspeicher, VMs und VM-Datenspeicher.

Wenn Sie SnapCenter oder SnapCenter für VMware verwenden, werden alle von diesen Produkten unterstützten Workloads auch in Ransomware Resilience identifiziert. Ransomware Resilience kann SnapCenter und SnapCenter -Workloads auf eine workloadkonsistente Weise schützen und wiederherstellen.

.Wie ordnet man Daten einer Arbeitslast zu?
Ransomware Resilience erkennt die Volumes und die Dateierweiterungen und ordnet sie der entsprechenden Arbeitslast zu.

Wenn Sie SnapCenter oder SnapCenter for VMware besitzen und Workloads in Backup and Recovery konfiguriert haben, erkennt Ransomware Resilience die von SnapCenter und SnapCenter for VMware verwalteten Workloads sowie die zugehörigen Volumes.

.Was ist eine geschützte Arbeitslast?
In Ransomware Resilience wird eine Arbeitslast als *geschützt* angezeigt, wenn eine primäre Erkennungsrichtlinie aktiviert ist, was bedeutet: link:concept-ransomware-resilience.html["Autonomer Ransomware-Schutz (ARP)"] ist auf allen Volumes aktiviert, die mit der Arbeitslast zusammenhängen.

.Was ist eine „gefährdete“ Arbeitsbelastung?
Wenn für eine Arbeitslast keine primäre Erkennungsrichtlinie aktiviert ist, wird sie als "gefährdet" gekennzeichnet, selbst wenn eine Backup- und Snapshot-Richtlinie aktiviert ist. Zum Schutz vor Ransomware sollten Sie Folgendes aktivieren: link:rp-use-protect.html#add-a-ransomware-protection-strategy["Erkennungsrichtlinie"]Die

.Ich habe einen neuen Band hinzugefügt, aber er wird noch nicht angezeigt. Was soll ich tun?
Wenn Sie Ihrer Umgebung ein neues Volume hinzugefügt haben, starten Sie die Erkennung der Arbeitslast erneut. Nachdem das Volumen entdeckt wurde, link:rp-use-protect.html#add-a-ransomware-protection-strategy["Schutzrichtlinien anwenden, um das neue Volumen zu schützen"]Die



== Schutzrichtlinien

.Können Ransomware-Resilienzrichtlinien mit anderen Arten von Workload-Richtlinien koexistieren?
Derzeit unterstützt Backup und Recovery (Cloud Backup) eine Backup-Richtlinie pro Volume. Wenn Sie den Backup-Schutz mit Backup und Wiederherstellung konfigurieren, werden die Backup-Richtlinien mit Ransomware Resilience geteilt.

Snapshot-Kopien sind nicht begrenzt und können von jedem Dienst separat hinzugefügt werden.

.Welche Richtlinien sind in einer Ransomware-Schutzstrategie erforderlich?
A link:rp-use-protect.html#add-a-ransomware-protection-strategy["Ransomware-Schutzstrategie"] erfordert:

* eine Ransomware-Erkennungsrichtlinie und
* eine Snapshot-Richtlinie


Eine Backup-Richtlinie ist in der Ransomware-Resilience-Strategie nicht erforderlich.

.Ist die Ransomware-Resilienz auf die Schutzeinstellungen in ONTAP vorbereitet?
Ja, Ransomware Resilience erkennt in ONTAP festgelegte Snapshot-Zeitpläne. Es ermittelt außerdem, ob ARP und FPolicy auf allen Volumes einer erkannten Arbeitslast aktiviert sind. Die im Ransomware Resilience Dashboard angezeigten Informationen werden aus anderen NetApp -Lösungen und -Produkten zusammengeführt.

.Ist Ransomware Resilience mit den bereits in Backup and Recovery und SnapCenter festgelegten Richtlinien vertraut?
Ja, wenn Sie Workloads in Backup and Recovery oder SnapCenter verwalten, werden die von diesen Produkten verwalteten Richtlinien in Ransomware Resilience übernommen.

.Können die von NetApp Backup and Recovery und/oder SnapCenter übernommenen Richtlinien geändert werden?
Nein, Sie können von Ransomware Resilience aus keine von Backup and Recovery oder SnapCenter verwalteten Richtlinien ändern.  Sie verwalten alle Änderungen an diesen Richtlinien in Backup and Recovery oder SnapCenter.

.Falls in ONTAP Richtlinien vorhanden sind (wie ARP, FPolicy und Snapshots), werden diese in Ransomware Resilience geändert?
Nein. Ransomware Resilience ändert keine vorhandenen Erkennungsrichtlinien (ARP-, FPolicy-Einstellungen) von ONTAP.

.Was passiert, wenn Sie nach der Anmeldung für Ransomware Resilience neue Richtlinien in Backup and Recovery oder SnapCenter hinzufügen?
Ransomware Resilience erkennt neu erstellte Richtlinien und Richtlinienänderungen in Backup and Recovery oder SnapCenter.

.Können Richtlinien über ONTAP geändert werden?
Ja, Sie können Richtlinien von ONTAP in Ransomware Resilience ändern.  Sie können in Ransomware Resilience auch neue Richtlinien erstellen und auf Workloads anwenden.  Diese Aktion ersetzt vorhandene ONTAP -Richtlinien durch die in Ransomware Resilience erstellten Richtlinien.

.Kann man Richtlinien in ONTAP deaktivieren?
Sie können ARP in Erkennungsrichtlinien über die System Manager-Benutzeroberfläche, APIs oder CLI in ONTAP deaktivieren.

Sie können FPolicy- und Sicherungsrichtlinien deaktivieren, indem Sie eine andere Richtlinie anwenden, die diese nicht enthält.
