---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: Um Ransomware Resilience zu verwenden, führen Sie zur Einrichtung einige Schritte aus. 
---
= Einrichten von NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Die NetApp Ransomware Resilience wird eingerichtet, indem ein Backup-Ziel vorbereitet, die Voraussetzungen überprüft und die NetApp Console sowie der Console Agent konfiguriert werden.



[[prepare-the-backup-destination]]
== Vorbereiten des Sicherungsziels

Bereiten Sie eines der folgenden Sicherungsziele vor:

* NetApp StorageGRID
* Amazon Web Services
* Google Cloud Platform
* Microsoft Azure


Nachdem Sie die Optionen im Backup-Ziel selbst konfiguriert haben, konfigurieren Sie es später als Backup-Ziel in Ransomware Resilience. Weitere Informationen zur Konfiguration des Backup-Ziels in Ransomware Resilience finden Sie unter link:task-backup-destination.html["Konfigurieren von Sicherungszielen"].



[[prepare-storagegrid-to-become-a-backup-destination]]
=== Bereiten Sie StorageGRID als Backup-Ziel vor

Wenn Sie StorageGRID als Backup-Ziel verwenden möchten, lesen Sie https://docs.netapp.com/us-en/storagegrid-117/index.html["StorageGRID -Dokumentation"^] für Details zu StorageGRID.



[[prepare-aws-to-become-a-backup-destination]]
=== Bereiten Sie AWS darauf vor, ein Backup-Ziel zu werden

* Richten Sie ein Konto in AWS ein.
* Konfigurieren https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS-Berechtigungen"^] in AWS.


Weitere Informationen zur Verwaltung Ihres AWS-Speichers in der Konsole finden Sie unter https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Verwalten Sie Ihre Amazon S3-Buckets"^] .



[[prepare-azure-to-become-a-backup-destination]]
=== Bereiten Sie Azure als Sicherungsziel vor

* Richten Sie ein Konto in Azure ein.
* Konfigurieren https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Azure-Berechtigungen"^] in Azure.


Weitere Informationen zur Verwaltung Ihres Azure-Speichers in der Konsole finden Sie unter https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Verwalten Ihrer Azure-Speicherkonten"^] .



[[set-up-the-netapp-console]]
== Einrichten der NetApp Console

Der nächste Schritt ist die Einrichtung der NetApp Console und Ransomware Resilience.

Rezension https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Konsolenanforderungen für den Standardmodus"^] .



[[create-a-console-agent]]
=== Erstellen eines Konsolenagenten

Wenden Sie sich an Ihren NetApp Vertriebsmitarbeiter, um diesen Service zu testen oder zu nutzen. Dann umfasst der Console Agent die erforderlichen Funktionen für Ransomware Resilience.

Um einen Console Agent für Ransomware Resilience zu erstellen, sollte der Console Organisationsadministrator mit Berechtigung zur Erstellung von Console Agenten kontaktiert werden, und es wird auf  https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["So erstellen Sie einen Konsolenagenten"^] verwiesen.


NOTE: Wenn Sie mehrere Console-Agenten verwenden, scannt Ransomware Resilience Daten über alle Console-Agenten hinweg, nicht nur über den aktuell in der Console angezeigten. Der Dienst scannt Daten über alle Projekte und Console-Agenten, die mit der Organisation verknüpft sind.
