---
sidebar: sidebar 
permalink: rp-use-overview.html 
keywords: ransomware protection, ransomware protection, detect ransomware attacks, recover from ransomware attack 
summary: Mit NetApp Ransomware Resilience können Sie den Zustand der Workloads anzeigen und diese schützen. 
---
= Nutzen Sie NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Mit NetApp Ransomware Resilience können Sie den Zustand Ihrer Workloads einsehen und diese schützen.

* link:rp-start-discover.html["Entdecken Sie Workloads in Ransomware Resilience"] .
* link:rp-use-dashboard.html["Schutz und Workload-Integrität vom Dashboard aus anzeigen"] .
+
** Lesen Sie die Empfehlungen zum Schutz vor Ransomware und setzen Sie diese um.


* link:rp-use-protect.html["Workloads schützen"]:
+
** Weisen Sie Workloads eine Ransomware-Schutzstrategie zu.
** Erhöhen Sie den Anwendungsschutz, um zukünftige Ransomware-Angriffe zu verhindern.
** Erstellen, ändern oder löschen Sie eine Schutzstrategie.


* link:rp-use-alert.html["Reagieren Sie auf die Erkennung potenzieller Ransomware-Angriffe"] .
* link:rp-use-recover.html["Wiederherstellung nach einem Angriff"](nachdem Vorfälle neutralisiert wurden).
* link:rp-use-settings.html["Konfigurieren der Schutzeinstellungen"] .

