---
sidebar: sidebar 
permalink: task-automate-user-activity.html 
keywords: data breach detection, data breach, user activity, automated response, block user, automate, ransomware response 
summary: NetApp Ransomware Resilience unterstützt das Erstellen automatisierter Reaktionen auf Benutzeraktivitätsereignisse, sodass automatisch ein Snapshot erstellt oder ein Benutzer gesperrt werden kann. 
---
= Automatisierte Reaktionen auf Benutzeraktivitätswarnungen in NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Mit NetApp Ransomware Resilience können Reaktionen auf link:concept-user-behavior.html["Benutzeraktivitätsereignisse"] automatisiert werden. Wenn eine Benutzeraktivitätswarnung ausgelöst wird, kann Ransomware Resilience Folgendes ausführen:

* Einen Benutzer blockieren
* Erstellen Sie einen Snapshot


Automatisierte Reaktionen werden bei Verschlüsselung (Benutzerverhalten), Datenschutzverletzungen und Datenzerstörung unterstützt. Es müssen link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#create-a-user-activity-agent["einen Benutzeraktivitätsagenten konfiguriert, eine Richtlinie mit Benutzeraktivitätserkennung aktiviert und einen Benutzerverzeichnis-Connector erstellt"] vorhanden sein, bevor eine automatisierte Reaktion erstellt werden kann. Wenn eine automatisierte Reaktion ausgelöst wird, sendet NetApp Ransomware Resilience eine E-Mail-Benachrichtigung.


NOTE: Wird die Warnung durch verdächtiges Nutzerverhalten ausgelöst, kann lediglich eine Snapshot erstellt werden. Das Sperren eines Nutzers ist als automatische Reaktion auf verdächtiges Nutzerverhalten nicht möglich.



[[create-an-automated-response]]
== Eine automatisierte Antwort erstellen

Es kann nur eine Storage-VM mit mindestens einer Arbeitslast geschützt werden, die durch eine Richtlinie zur Erkennung verdächtigen Benutzerverhaltens geschützt ist.

.Schritte
. Unter Ransomware Resilience wählen Sie **Einstellungen**.
. Im Feld „Benutzeraktivitätsüberwachung“ **Verwalten** auswählen.
. Die Registerkarte **Automatisierte Antworten** auswählen.
. **Hinzufügen** auswählen, um das Verhalten zu erstellen.
. Einen **Namen** für die automatisierte Antwort eingeben.
. Wählen Sie den Ereignistyp, der die Reaktion auslöst: **Angriff** oder **Warnung**. Weitere Informationen zu den verschiedenen link:rp-use-alert.html#alert-types-and-statuses["Arten von Warnungen"].
. Wählen Sie die Antwort aus:
+
** **Benutzerzugriff sperren**: Der Benutzer wird von allen durch NetApp Ransomware Resilience geschützten Storage-VMs gesperrt, wenn die Warnung ausgelöst wird.
+
Wenn Sie diese Option wählen, müssen Sie auch die Dauer der Sperre festlegen. Diese kann zwischen 1 und 24 Stunden oder dauerhaft sein.

** **Snapshots erstellen**: Ein Snapshot der betroffenen Workloads wird zur möglichen Wiederherstellung erstellt. Die Snapshots werden sieben Tage lang aufbewahrt.


. Wählen Sie die Alarmtypen aus, die die automatisierte Reaktion auslösen:
+
|===


| Alarmtyp | Beschreibung 


| Verschlüsselung (Benutzerverhalten) | Ransomware Resilience erkennt anomale Lese-, Schreib- und Umbenennungsaktivitäten von Dateien, die von einem bestimmten Benutzer durchgeführt werden. 


| Datenpanne | Ransomware Resilience erkennt anomale Dateilesemuster, die von einem bestimmten Benutzer durchgeführt werden. 


| Datenvernichtung | Ransomware Resilience erkennt die massenhafte Löschung von Dateien durch einen bestimmten Benutzer. 


| Verdächtiges Nutzerverhalten | Ransomware Resilience identifiziert anomales Verhalten, das über den Rahmen von Datenlecks, Datenzerstörung oder Verschlüsselung hinausgeht. 
|===
. Wählen Sie die Storage-VMs aus, auf die die automatisierte Antwort angewendet werden soll.
. **Hinzufügen** auswählen, um die automatische Antwort zu erstellen.




[[modify-an-automated-response]]
== Eine automatisierte Antwort ändern

Nachdem eine automatische Antwort erstellt wurde, besteht die Möglichkeit, die Antwort zu pausieren, neu zu starten oder zu ändern. Der Name der Antwort, die Alarmtypen, die die Antwort auslösen, die Storage-VMs und die durchgeführte Aktion können geändert werden.

.Schritte
. Unter Ransomware Resilience wählen Sie **Einstellungen**.
. Im Feld „Benutzeraktivitätsüberwachung“ **Verwalten** auswählen.
. Die Registerkarte **Automatisierte Antworten** auswählen.
. Wählen Sie die automatisierte Antwort aus, die Sie ändern möchten.
. Um die Antwort anzuhalten oder zu löschen, im Aktionsmenü **Pause** (oder **Start**) oder **Löschen** auswählen.
+
Um die Antwort zu ändern, **Bearbeiten** auswählen.

. Sie können alle Einstellungen ändern, außer dem Schweregrad des Alarms.
. **Speichern** auswählen, um die Änderungen zu übernehmen.




[[next-steps]]
== Nächste Schritte

link:task-users-manage.html["Blockierte Benutzer verwalten"]
