= Aktivieren Sie die Datenklassifizierung und suchen Sie nach personenbezogenen Daten (PII).
:allow-uri-read: 




=== Aktivieren Sie die Datenklassifizierung und suchen Sie nach personenbezogenen Daten (PII).

Mit dieser Version können Sie die BlueXP classification, eine Kernkomponente der BlueXP Familie, aktivieren, um Daten in Ihren Dateifreigabe-Workloads zu scannen und zu klassifizieren.  Durch die Klassifizierung von Daten können Sie feststellen, ob Ihre Daten persönliche oder private Informationen enthalten, die das Sicherheitsrisiko erhöhen können.  Dieser Prozess wirkt sich auch auf die Wichtigkeit der Arbeitslast aus und hilft Ihnen sicherzustellen, dass Sie die Arbeitslasten mit dem richtigen Schutzniveau schützen.

Das Scannen nach PII-Daten im BlueXP ransomware protection ist im Allgemeinen für Kunden verfügbar, die die BlueXP classification eingesetzt haben.  Die BlueXP classification ist als Teil der BlueXP Plattform ohne zusätzliche Kosten verfügbar und kann vor Ort oder in der Kunden-Cloud bereitgestellt werden.

Um den Scan zu starten, wählen Sie auf der Seite Schutz im Dashboard des Schutzes in der Spalte Datenschutzrisiken die Option Identify exposure. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-classify.html["Scannen Sie nach personenbezogenen sensiblen Daten mit BlueXP classification"].



=== SIEM-Integration mit Microsoft Sentinel

Sie können jetzt mithilfe von Microsoft Sentinel Daten zur Bedrohungsanalyse und -erkennung an Ihr Sicherheits- und Ereignismanagementsystem (SIEM) senden.  Bisher konnten Sie den AWS Security Hub oder Splunk Cloud als Ihr SIEM auswählen.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Erfahren Sie mehr über die Konfiguration der BlueXP ransomware protection -Schutzeinstellungen"].



=== Jetzt 30 Tage kostenlos testen

Mit dieser Version können neue Bereitstellungen des BlueXP ransomware protection jetzt 30 Tage lang kostenlos getestet werden.  Zuvor war der BlueXP ransomware protection 90 Tage lang als kostenlose Testversion verfügbar.  Wenn Sie bereits an der 90-tägigen kostenlosen Testversion teilnehmen, gilt dieses Angebot für die nächsten 90 Tage.
