= Sicherheitsrisikobewertung von Digital Advisor
:allow-uri-read: 




[[security-risk-assessment-from-digital-advisor]]
=== Sicherheitsrisikobewertung von Digital Advisor

BlueXP Ransomware Protection sammelt nun Informationen über hohe und kritische Cluster-Sicherheitsrisiken von NetApp Digital Advisor. Wenn ein Risiko erkannt wird, zeigt BlueXP Ransomware Protection im Dashboard im Bereich *Empfohlene Aktionen* die folgende Empfehlung an: „Bekannte Sicherheitslücke im Cluster beheben <name>.“ Aus der Dashboard-Empfehlung kann *Überprüfen und beheben* ausgewählt werden, um Digital Advisor und den zugehörigen Common Vulnerability & Exposure (CVE) Artikel einzusehen. Bei mehreren Sicherheitsrisiken können die Details in Digital Advisor eingesehen werden.

Siehe https://docs.netapp.com/us-en/active-iq/index.html["Digital Advisor -Dokumentation"^] .



[[back-up-to-google-cloud-platform]]
=== Sichern Sie auf der Google Cloud Platform

Mit dieser Version können Sie als Sicherungsziel einen Bucket der Google Cloud Platform festlegen.  Bisher konnten Sie Sicherungsziele nur zu NetApp StorageGRID, Amazon Web Services und Microsoft Azure hinzufügen.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-backup-destination.html["Erfahren Sie mehr über die Konfiguration der BlueXP ransomware protection -Schutzeinstellungen"].



[[support-for-google-cloud-platform]]
=== Unterstützung für Google Cloud Platform

Der Dienst unterstützt jetzt Cloud Volumes ONTAP für Google Cloud Platform zum Speicherschutz.  Zuvor unterstützte der Dienst nur Cloud Volumes ONTAP für Amazon Web Services und Microsoft Azure sowie lokales NAS.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Erfahren Sie mehr über den BlueXP ransomware protection und die unterstützten Datenquellen, Sicherungsziele und Arbeitsumgebungen"] .



[[role-based-access-control]]
=== Rollenbasierte Zugriffskontrolle

Sie können jetzt den Zugriff auf bestimmte Aktivitäten mit der rollenbasierten Zugriffskontrolle (RBAC) beschränken.  Der BlueXP ransomware protection verwendet zwei Rollen von BlueXP: BlueXP Kontoadministrator und Nicht-Kontoadministrator (Viewer).

Einzelheiten zu den Aktionen, die jede Rolle ausführen kann, finden Sie unter https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["Rollenbasierte Zugriffskontrollberechtigungen"] .
