= Sicherheitsrisikobewertung von Digital Advisor
:allow-uri-read: 




=== Sicherheitsrisikobewertung von Digital Advisor

BlueXP ransomware protection sammelt nun Informationen über hohe und kritische Sicherheitsrisiken im Zusammenhang mit einem Cluster von NetApp Digital Advisor. Wenn ein Risiko gefunden wird, gibt BlueXP ransomware protection eine Empfehlung im Bereich *Empfohlene Aktionen* des Dashboards: „Bekannte Sicherheitslücke im Cluster beheben <name>.“ Von der Empfehlung im Dashboard aus schlägt die Auswahl von *Überprüfen und beheben* vor, Digital Advisor und einen Common Vulnerability & Exposure (CVE)-Artikel zu überprüfen, um das Sicherheitsrisiko zu beheben. Wenn mehrere Sicherheitsrisiken bestehen, überprüfen Sie die Informationen in Digital Advisor.

Siehe https://docs.netapp.com/us-en/active-iq/index.html["Digital Advisor -Dokumentation"^] .



=== Sichern Sie auf der Google Cloud Platform

Mit dieser Version können Sie als Sicherungsziel einen Bucket der Google Cloud Platform festlegen.  Bisher konnten Sie Sicherungsziele nur zu NetApp StorageGRID, Amazon Web Services und Microsoft Azure hinzufügen.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-settings.html["Erfahren Sie mehr über die Konfiguration der BlueXP ransomware protection -Schutzeinstellungen"] .



=== Unterstützung für Google Cloud Platform

Der Dienst unterstützt jetzt Cloud Volumes ONTAP für Google Cloud Platform zum Speicherschutz.  Zuvor unterstützte der Dienst nur Cloud Volumes ONTAP für Amazon Web Services und Microsoft Azure sowie lokales NAS.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Erfahren Sie mehr über den BlueXP ransomware protection und die unterstützten Datenquellen, Sicherungsziele und Arbeitsumgebungen"] .



=== Rollenbasierte Zugriffskontrolle

Sie können jetzt den Zugriff auf bestimmte Aktivitäten mit der rollenbasierten Zugriffskontrolle (RBAC) beschränken.  Der BlueXP ransomware protection verwendet zwei Rollen von BlueXP: BlueXP Kontoadministrator und Nicht-Kontoadministrator (Viewer).

Einzelheiten zu den Aktionen, die jede Rolle ausführen kann, finden Sie unter https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["Rollenbasierte Zugriffskontrollberechtigungen"] .
