= Simulieren Sie einen Angriff und reagieren Sie darauf
:allow-uri-read: 




=== Simulieren Sie einen Angriff und reagieren Sie darauf

Simulieren Sie mit dieser Version einen Ransomware-Angriff, um Ihre Reaktion auf eine Ransomware-Warnung zu testen.  Mithilfe dieser Funktion können Sie durch das Testen von Warnbenachrichtigungen, Reaktions- und Wiederherstellungsprozessen sicherstellen, dass Sie im Falle eines tatsächlichen Ransomware-Angriffs vorbereitet sind.

Weitere Einzelheiten finden Sie unter https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-simulate.html["Führen Sie eine Übung zur Vorbereitung auf Ransomware-Angriffe durch"] .



=== Verbesserungen des Erkennungsprozesses

Diese Version enthält Verbesserungen der selektiven Erkennungs- und Neuerkennungsprozesse:

* Mit dieser Version können Sie neu erstellte Workloads entdecken, die den zuvor ausgewählten Arbeitsumgebungen hinzugefügt wurden.
* Sie können in dieser Version auch _neue_ Arbeitsumgebungen auswählen.  Mit dieser Funktion können Sie neue Workloads schützen, die Ihrer Umgebung hinzugefügt werden.
* Sie können diese Erkennungsprozesse während des Erkennungsprozesses zu Beginn oder innerhalb der Option „Einstellungen“ durchführen.


Weitere Einzelheiten finden Sie unter https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-discover.html["Entdecken Sie neu erstellte Workloads für zuvor ausgewählte Arbeitsumgebungen"] Und https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-settings.html["Konfigurieren von Funktionen mit der Option „Einstellungen“"] .



=== Warnungen werden ausgelöst, wenn eine hohe Verschlüsselung erkannt wird

Mit dieser Version können Sie Warnmeldungen anzeigen, wenn bei Ihren Workloads eine hohe Verschlüsselung erkannt wird, auch ohne dass es zu starken Änderungen der Dateierweiterungen kommt.  Diese Funktion, die ONTAP Autonomous Ransomware Protection (ARP) AI verwendet, hilft Ihnen, Workloads zu identifizieren, die einem Risiko von Ransomware-Angriffen ausgesetzt sind.  Verwenden Sie diese Funktion und laden Sie die gesamte Liste der betroffenen Dateien mit oder ohne Erweiterungsänderungen herunter.

Weitere Einzelheiten finden Sie unter https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Reagieren Sie auf eine erkannte Ransomware-Warnung"] .
