= Die Blockierung von Erweiterungen ist auf Workload-Ebene aktiviert.
:allow-uri-read: 




[[extension-blocking-is-enabled-at-the-workload-level]]
=== Die Blockierung von Erweiterungen ist auf Workload-Ebene aktiviert.

Wenn Sie die Erweiterungsblockierung aktivieren, erfolgt die Aktivierung nun auf Workload-Ebene und nicht mehr auf Ebene der Speicher-VM.



[[edit-user-behavior-alert-status]]
=== Benutzerverhaltenswarnungsstatus bearbeiten

Ransomware Resilience ermöglicht es Ihnen nun, den Status von Warnmeldungen zum Benutzerverhalten zu bearbeiten. Sie können Warnmeldungen manuell verwerfen und beheben.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Warnmeldungen in der Ransomware-Resilienz verwalten"^].



[[support-for-multiple-console-agents]]
=== Unterstützung für mehrere Konsolenagenten

Ransomware Resilience unterstützt jetzt die Verwendung mehrerer Console-Agenten zur Verwaltung derselben Systeme.

Weitere Informationen zu Console-Agenten finden Sie unterlink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-setup.html["Erstellen eines Konsolenagenten"] Die
