= Google Cloud NetApp Volumes-Unterstützung (Vorschau)
:allow-uri-read: 




[[google-cloud-netapp-volumes-support-preview]]
=== Google Cloud NetApp Volumes-Unterstützung (Vorschau)

Ransomware Resilience unterstützt jetzt Google Cloud NetApp Volumes-Systeme und ermöglicht Ihnen so die effiziente Erkennung und Abwehr von Ransomware-Bedrohungen in Google Cloud NetApp Volumes. Bei der Erkennung zeigt Ransomware Resilience automatisch Workloads aus Google Cloud NetApp Volumes-Systemen an. Die erkannten Systeme werden im Ransomware Resilience-Dashboard angezeigt. Die Unterstützung für Google Cloud NetApp Volumes in Ransomware Resilience befindet sich derzeit in der Vorschauphase.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Erfahren Sie mehr über Ransomware-Resilienz"^]. Informationen zum Umfang der Google Cloud NetApp Volumes-Unterstützung finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["Einschränkungen der Ransomware-Resilienz"^].



[[clean-restore-enhancements]]
=== Verbesserungen für Clean Restore

Die Funktion „Saubere Wiederherstellung“ unterstützt jetzt Berichte. Mithilfe von Berichten können Sie saubere Wiederherstellungen überprüfen und bewerten und diese Informationen offline als CSV-Datei speichern.

Die saubere Wiederherstellung unterstützt nun auch das Anhalten der Analyse. Wenn Sie die Analyse anhalten, müssen Sie die saubere Wiederherstellung erneut starten.

Weitere Informationen zu Berichten finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Berichte zum Thema Ransomware-Resilienz herunterladen"^]. Weitere Informationen zur Wiederherstellung finden Sie unter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Stellen Sie Workloads mit einer sauberen Wiederherstellung wieder her"^].
